"""initial schema

Revision ID: 41da551de8e5
Revises: 
Create Date: 2026-05-10 19:09:28.979081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41da551de8e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anon_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('binary_path', sa.Text(), nullable=False),
    sa.Column('weights_path', sa.Text(), nullable=True),
    sa.Column('build_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index("idx_users_username_lower", "users", [sa.text("LOWER(username)")], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anon_session_id', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('side', sa.Integer(), nullable=False),
    sa.Column('opponent_kind', sa.String(length=16), nullable=False),
    sa.Column('opponent_ref', sa.String(length=128), nullable=True),
    sa.Column('engine_level', sa.String(length=16), nullable=False),
    sa.Column('clock_initial_ms', sa.Integer(), nullable=False),
    sa.Column('clock_increment_ms', sa.Integer(), nullable=False),
    sa.Column('clock_white_ms', sa.Integer(), nullable=False),
    sa.Column('clock_black_ms', sa.Integer(), nullable=False),
    sa.Column('last_clock_at', sa.DateTime(), nullable=True),
    sa.Column('start_fen', sa.Text(), nullable=False),
    sa.Column('current_fen', sa.Text(), nullable=False),
    sa.Column('current_ply', sa.Integer(), nullable=False),
    sa.Column('side_to_move', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=True),
    sa.Column('result_reason', sa.String(length=32), nullable=True),
    sa.Column('final_score', sa.String(length=16), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(user_id IS NOT NULL AND anon_session_id IS NULL) OR (user_id IS NULL AND anon_session_id IS NOT NULL)', name='games_owner_xor'),
    sa.ForeignKeyConstraint(['anon_session_id'], ['anon_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index('idx_games_active', ['status'], unique=False)
        batch_op.create_index('idx_games_anon', ['anon_session_id', 'started_at'], unique=False)
        batch_op.create_index('idx_games_user', ['user_id', 'started_at'], unique=False)

    op.create_table('game_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('ply_at', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.create_index('idx_events_game', ['game_id', 'created_at'], unique=False)

    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('side', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=16), nullable=False),
    sa.Column('move_uci', sa.String(length=8), nullable=False),
    sa.Column('fen_after', sa.Text(), nullable=False),
    sa.Column('eval_cp', sa.Integer(), nullable=True),
    sa.Column('eval_depth', sa.Integer(), nullable=True),
    sa.Column('pv', sa.Text(), nullable=True),
    sa.Column('think_time_ms', sa.Integer(), nullable=True),
    sa.Column('clock_after_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'ply')
    )
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.create_index('idx_moves_game', ['game_id', 'ply'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.drop_index('idx_moves_game')

    op.drop_table('moves')
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.drop_index('idx_events_game')

    op.drop_table('game_events')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index('idx_games_user')
        batch_op.drop_index('idx_games_anon')
        batch_op.drop_index('idx_games_active')

    op.drop_table('games')
    op.drop_index("idx_users_username_lower", "users")
    op.drop_table('users')
    op.drop_table('engines')
    op.drop_table('anon_sessions')
    # ### end Alembic commands ###
