"""
Training script for TogyzNet V2 (Gumbel AlphaZero).

Loads self-play data generated by the Rust engine and trains the dual-head
neural network with policy cross-entropy + value MSE + entropy regularization.
"""

import argparse
import os

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader

from model import TogyzNetV2, FEATURE_SIZE, NUM_ACTIONS
from dataset import SelfPlayDataset


def train(args):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Training on: {device}")

    # Load or create model
    model = TogyzNetV2(
        input_size=FEATURE_SIZE,
        hidden_size=args.hidden_size,
        num_blocks=args.num_blocks,
    ).to(device)

    if args.model_in and os.path.exists(args.model_in):
        model.load_state_dict(torch.load(args.model_in, map_location=device))
        print(f"Loaded model from {args.model_in}")
    else:
        print(f"Training from scratch. Parameters: {model.count_parameters():,}")

    # Data
    dataset = SelfPlayDataset(args.data)
    loader = DataLoader(
        dataset, batch_size=args.batch_size, shuffle=True, num_workers=4, pin_memory=True
    )
    print(f"Dataset: {len(dataset):,} samples, {len(loader)} batches")

    # Optimizer
    optimizer = optim.Adam(
        model.parameters(), lr=args.lr, weight_decay=args.weight_decay
    )
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, args.epochs)

    # Training loop
    best_loss = float("inf")

    for epoch in range(args.epochs):
        model.train()
        total_loss = 0.0
        total_value_loss = 0.0
        total_policy_loss = 0.0
        total_entropy = 0.0
        num_batches = 0

        for features, target_policy, target_value in loader:
            features = features.to(device)
            target_policy = target_policy.to(device)
            target_value = target_value.to(device)

            # Forward pass
            pred_logits, pred_value = model(features)

            # Value loss: MSE
            value_loss = nn.MSELoss()(pred_value.squeeze(-1), target_value)

            # Policy loss: cross-entropy with soft targets
            log_probs = torch.log_softmax(pred_logits, dim=1)
            policy_loss = -(target_policy * log_probs).sum(dim=1).mean()

            # Entropy regularization
            probs = torch.softmax(pred_logits, dim=1)
            entropy = -(probs * torch.log(probs + 1e-8)).sum(dim=1).mean()

            # Total loss
            loss = value_loss + policy_loss - args.entropy_coeff * entropy

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            total_loss += loss.item()
            total_value_loss += value_loss.item()
            total_policy_loss += policy_loss.item()
            total_entropy += entropy.item()
            num_batches += 1

        scheduler.step()

        avg_loss = total_loss / max(num_batches, 1)
        avg_vloss = total_value_loss / max(num_batches, 1)
        avg_ploss = total_policy_loss / max(num_batches, 1)
        avg_entropy = total_entropy / max(num_batches, 1)

        print(
            f"Epoch {epoch+1}/{args.epochs} | "
            f"Loss: {avg_loss:.4f} | "
            f"Value: {avg_vloss:.4f} | "
            f"Policy: {avg_ploss:.4f} | "
            f"Entropy: {avg_entropy:.4f} | "
            f"LR: {scheduler.get_last_lr()[0]:.6f}"
        )

        if avg_loss < best_loss:
            best_loss = avg_loss

    # Save
    torch.save(model.state_dict(), args.model_out)
    print(f"Saved model to {args.model_out}")
    print(f"Best loss: {best_loss:.4f}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train TogyzNet V2")
    parser.add_argument("--data", required=True, help="Path to self-play data (.bin)")
    parser.add_argument("--model-in", default=None, help="Input model weights (.pt)")
    parser.add_argument(
        "--model-out", required=True, help="Output model weights (.pt)"
    )
    parser.add_argument("--epochs", type=int, default=10)
    parser.add_argument("--batch-size", type=int, default=512)
    parser.add_argument("--lr", type=float, default=0.001)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--entropy-coeff", type=float, default=0.01)
    parser.add_argument("--hidden-size", type=int, default=256)
    parser.add_argument("--num-blocks", type=int, default=6)
    train(parser.parse_args())
